/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainscreen;

import javax.swing.JOptionPane;
import model.dao.LoginInfoDao;
import model.to.LoginInfoTo;
import useit.Validations;

/**
 *
 * @author Rahul Saini
 */
public class IfAddUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfAddUser
     */
    public IfAddUser() {
        initComponents();
        login_combo.removeAllItems();
        login_combo.addItem("CHOOSE ONE");
        login_combo.addItem("ADMIN");
        login_combo.addItem("USER");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_login1 = new javax.swing.JLabel();
        tf_login1 = new javax.swing.JTextField();
        lb_login2 = new javax.swing.JLabel();
        tf_login2 = new javax.swing.JTextField();
        lb_login3 = new javax.swing.JLabel();
        login_combo = new javax.swing.JComboBox();
        bt_login = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        lb_login1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_login1.setText("ENTER USERNAME :");

        tf_login1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lb_login2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_login2.setText("ENTER PASSWORD :");

        tf_login2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lb_login3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_login3.setText("CHOOSE ROLE_NAME :");

        login_combo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        login_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bt_login.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon.png"))); // NOI18N
        bt_login.setText("CREATE USER");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go-back-icon.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(bt_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_login3)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lb_login1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lb_login2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(login_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_login1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(tf_login2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_login1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_login2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_login2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_login3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        String msg ="";
        String username=tf_login1.getText().trim();
        String password=tf_login2.getText().trim();
        LoginInfoTo record=new LoginInfoTo();
        if(Validations.isEmpty(username)||Validations.isEmpty(password))
        {
            msg+="PLEASE FILL ALL BOXES";
        }
        else
        {
            record.setUser_name(username);
            record.setPassword_set(password);
        }
        if(login_combo.getSelectedIndex()==0)
        {
            msg+="PLEASE CHOOSE ROLE NAME";
        }
        else
        {
            String role_name=(String)login_combo.getSelectedItem();
            record.setRole_name(role_name);
        }   
        LoginInfoDao action=new LoginInfoDao();
        if(action.insertRecord(record))
        {
            msg+="USER IS CREATED \n";
        }  
        else
        {
            msg+="FAILURE";
        }   
        JOptionPane.showMessageDialog(this, msg);
    }//GEN-LAST:event_bt_loginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lb_login1;
    private javax.swing.JLabel lb_login2;
    private javax.swing.JLabel lb_login3;
    private javax.swing.JComboBox login_combo;
    private javax.swing.JTextField tf_login1;
    private javax.swing.JTextField tf_login2;
    // End of variables declaration//GEN-END:variables
}
