/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainscreen;

import java.sql.Date;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import model.dao.BillInfoDao;
import model.dao.CustomerDao;
import model.dao.LoginInfoDao;
import model.dao.MedicineInfoDao;
import model.dao.StockDao;
import model.dao.SupplierDao;
import model.to.BillInfoTo;
import model.to.CustomerTo;
import model.to.LoginInfoTo;
import model.to.MedicineInfoTo;
import model.to.StockTo;
import model.to.SupplierTo;
import useit.Validations;

/**
 *
 * @author Rahul Saini
 */
public class IfAddStock extends javax.swing.JInternalFrame {

    private List<MedicineInfoTo> meds;
    private List<SupplierTo> sup;
    private List<LoginInfoTo> log;
    public IfAddStock() {
        initComponents();
        combo_stock1.removeAllItems();
        combo_stock2.removeAllItems();
        combo_stock3.removeAllItems();
        combo_stock1.addItem("CHOOSE MEDICINE");
        MedicineInfoDao action1=new MedicineInfoDao();
        meds=action1.getAllRecord1();
        for(MedicineInfoTo med:meds)
        {
            combo_stock1.addItem(med);
        }
        
        combo_stock2.addItem("CHOOSE SUPPLIER");
        SupplierDao action2=new SupplierDao();
        sup=action2.getAllRecord();
        for(SupplierTo med:sup)
        {
            combo_stock2.addItem(med);
        }
        
        combo_stock3.addItem("CHOOSE USER");
        LoginInfoDao action3=new LoginInfoDao();
        log=action3.getAllRecord();
        for(LoginInfoTo logs:log)
        {
            combo_stock3.addItem(logs);
        }   
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_group = new javax.swing.ButtonGroup();
        lb_stock1 = new javax.swing.JLabel();
        tf_stock1 = new javax.swing.JTextField();
        combo_stock1 = new javax.swing.JComboBox();
        combo_stock2 = new javax.swing.JComboBox();
        lb_stock2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel3 = new controls.DatePanel();
        lb_stock3 = new javax.swing.JLabel();
        lb_stock4 = new javax.swing.JLabel();
        panel2 = new controls.DatePanel1();
        tf_stock2 = new javax.swing.JTextField();
        lb_stock5 = new javax.swing.JLabel();
        combo_stock3 = new javax.swing.JComboBox();
        lb_stock6 = new javax.swing.JLabel();
        tf_stock3 = new javax.swing.JTextField();
        lb_stock8 = new javax.swing.JLabel();
        lb_stock9 = new javax.swing.JLabel();
        rd_stock1 = new javax.swing.JRadioButton();
        rd_stock2 = new javax.swing.JRadioButton();
        bt_stock2 = new javax.swing.JButton();
        bt_stock1 = new javax.swing.JButton();
        lb_stock7 = new javax.swing.JLabel();
        panel1 = new controls.DatePanel();

        setClosable(true);
        setIconifiable(true);

        lb_stock1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_stock1.setText("CHOOSE MEDICINE :");
        lb_stock1.setToolTipText("");

        tf_stock1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        combo_stock1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combo_stock1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combo_stock2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combo_stock2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_stock2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_stock2ActionPerformed(evt);
            }
        });

        lb_stock2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_stock2.setText("CHOOSE SUPPLIER :");
        lb_stock2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("ENTER BATCH NO :");

        lb_stock3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_stock3.setText("CHOOSE MFD DATE :");
        lb_stock3.setToolTipText("");

        lb_stock4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_stock4.setText("CHOOSE EXP DATE :");
        lb_stock4.setToolTipText("");

        tf_stock2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lb_stock5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_stock5.setText("ENTER PRICE :");

        combo_stock3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combo_stock3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lb_stock6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_stock6.setText("UPDATED BY:");
        lb_stock6.setToolTipText("");

        tf_stock3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lb_stock8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_stock8.setText("ENTER QUANTITY :");

        lb_stock9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_stock9.setText("STOCK TYPE :");
        lb_stock9.setToolTipText("");

        bt_group.add(rd_stock1);
        rd_stock1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rd_stock1.setText("IN");

        bt_group.add(rd_stock2);
        rd_stock2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rd_stock2.setText("OUT");

        bt_stock2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_stock2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go-back-icon.png"))); // NOI18N
        bt_stock2.setText("BACK");
        bt_stock2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_stock2ActionPerformed(evt);
            }
        });

        bt_stock1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_stock1.setText("ADD STOCK");
        bt_stock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_stock1ActionPerformed(evt);
            }
        });

        lb_stock7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_stock7.setText("CHOOSE STOCK DATE :");
        lb_stock7.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_stock6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combo_stock3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_stock8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_stock3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(227, 227, 227)
                                    .addComponent(rd_stock1)
                                    .addGap(93, 93, 93)
                                    .addComponent(rd_stock2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_stock3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lb_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lb_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(combo_stock2, 0, 375, Short.MAX_VALUE)
                                            .addComponent(combo_stock1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tf_stock1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_stock4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_stock5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_stock2)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(bt_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(286, 286, 286)
                                    .addComponent(bt_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_stock7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_stock9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(488, 488, 488))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_stock1)
                    .addComponent(combo_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_stock2)
                    .addComponent(combo_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_stock3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_stock4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_stock5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_stock3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_stock8))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_stock6)
                    .addComponent(combo_stock3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_stock7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_stock9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rd_stock1)
                            .addComponent(rd_stock2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_stock2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_stock2ActionPerformed
        
    }//GEN-LAST:event_combo_stock2ActionPerformed

    private void bt_stock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_stock1ActionPerformed
       String msg="";
       StockTo record =new StockTo();
       StockDao action=new StockDao();
       MedicineInfoTo medicine=new MedicineInfoTo();
       MedicineInfoDao action1=new MedicineInfoDao();
       LoginInfoTo user=new LoginInfoTo();
       LoginInfoDao action2=new LoginInfoDao();
       
      if(combo_stock1.getSelectedIndex()==0)
      {
          msg+="PLEASE CHOOSE A MEDICINE \n";
      } 
      else
      {
         medicine=(MedicineInfoTo)combo_stock1.getSelectedItem();
         String medicine_code=medicine.getMedicine_code();
         record.setMedicine_code(medicine_code);
      }
      
      SupplierTo sup=new SupplierTo();
      if(combo_stock2.getSelectedIndex()==0)
      {
          msg+="PLEASE CHOOSE A SUPPLIER \n";
      } 
      else
      {
         sup=(SupplierTo)combo_stock2.getSelectedItem();
         String supplier_code=sup.getSupplier_code();
         record.setSupplier_code(supplier_code);
      }
      
      if(combo_stock3.getSelectedIndex()==0)
      {
          msg+="PLEASE CHOOSE USER \n";
      } 
      else
      {
         user=(LoginInfoTo)combo_stock3.getSelectedItem();
         String user_name=user.getUser_name();
         record.setUpdated_by(user_name);
      }
      String batch_no=tf_stock1.getText().trim();
      Date mfd_date=panel3.getSelectedDate();
      Date exp_date=panel2.getSelectedDate();
      Date stock_date=panel3.getSelectedDate();
      String price=tf_stock2.getText().trim();
      String qty=tf_stock3.getText().trim();
      String stocktype="";
        if(rd_stock1.isSelected())
        {
            stocktype="IN";
            record.setStock_type(stocktype);
        }
        else if(rd_stock2.isSelected()){
            stocktype="OUT";
            record.setStock_type(stocktype);
            
        }
        else
        {
            msg+="PLEASE CHOOSE STOCKTYPE \n";
        }
  
      
      if(Validations.isEmpty(batch_no)||exp_date==null||mfd_date==null||stock_date==null||Validations.isEmpty(price)||Validations.isEmpty(qty))
      {
          msg+="PLEASE FLLL OR CHOOSE ALL \n";
      }
      else
      {
          record.setBatch_no(batch_no);
          record.setMfd_date(mfd_date);
          record.setExp_date(exp_date);
          record.setStock_date(stock_date);
          record.setLast_updated(new Timestamp(System.currentTimeMillis()));   
      
          if(Validations.isFloat(price))
          {
            record.setPrice(Float.parseFloat(price));
          }
          else
          {
            msg+="PLEASE ENTER A VALID PRICE ";
          }
      
      
         if(Validations.isInteger(qty))
         {
           int q=Integer.parseInt(qty);
           if(q>0)
           {    
            record.setQty(q);
            if (stocktype.equalsIgnoreCase("IN")) {
                if (action.insertrecord(record)) {
                    medicine.setQty(medicine.getQty() + record.getQty());
                    System.out.println(medicine.getQty());
                    System.out.println(medicine.getMedicine_type());
                    System.out.println(medicine.getCompany_id());
                    
                    
                    if(action1.updaterecord(medicine))
                        {        
                        msg+= "MEDICINE is Added in Stock";
                        }
                }else{
                    msg+= " Failure due to : " + action.getError_message();
                 
                }
            } else {
                if (record.getQty() <= medicine.getQty())
                {
                    if (action.insertrecord(record)) 
                    {
                        medicine.setQty(medicine.getQty() - record.getQty());
                        if(action1.updaterecord(medicine))
                        {        
                        msg+= "MEDICINE is Added in Stock";
                        }
                    }    
                    else 
                    {
                        msg+=" Failure due to :"+ action.getError_message();
         
                    }
                }
              }
           }
         }
      else
      {
          msg+="ENTER VALID QUANTITY \n";
      }
     }
      
      
     JOptionPane.showMessageDialog(this, msg);
     
         
    }//GEN-LAST:event_bt_stock1ActionPerformed

    private void bt_stock2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_stock2ActionPerformed
     dispose();
    }//GEN-LAST:event_bt_stock2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bt_group;
    private javax.swing.JButton bt_stock1;
    private javax.swing.JButton bt_stock2;
    private javax.swing.JComboBox combo_stock1;
    private javax.swing.JComboBox combo_stock2;
    private javax.swing.JComboBox combo_stock3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_stock1;
    private javax.swing.JLabel lb_stock2;
    private javax.swing.JLabel lb_stock3;
    private javax.swing.JLabel lb_stock4;
    private javax.swing.JLabel lb_stock5;
    private javax.swing.JLabel lb_stock6;
    private javax.swing.JLabel lb_stock7;
    private javax.swing.JLabel lb_stock8;
    private javax.swing.JLabel lb_stock9;
    private controls.DatePanel panel1;
    private controls.DatePanel1 panel2;
    private controls.DatePanel panel3;
    private javax.swing.JRadioButton rd_stock1;
    private javax.swing.JRadioButton rd_stock2;
    private javax.swing.JTextField tf_stock1;
    private javax.swing.JTextField tf_stock2;
    private javax.swing.JTextField tf_stock3;
    // End of variables declaration//GEN-END:variables
}
