/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainscreen;

import java.util.List;
import javax.swing.JOptionPane;
import model.dao.BillInfoDao;
import model.dao.MedicineInfoDao;
import model.dao.SaleDetailDao;
import model.to.BillInfoTo;
import model.to.MedicineInfoTo;
import model.to.SaleDetailTo;
import static useit.Validations.isEmpty;
import static useit.Validations.isFloat;
import static useit.Validations.isInteger;

/**
 *
 * @author Rahul Saini
 */
public class IfAddSaleDetail extends javax.swing.JInternalFrame {

    private List<BillInfoTo> bills;
    private List<MedicineInfoTo> meds;
    public IfAddSaleDetail() {
        initComponents();
        combo_sales1.removeAllItems();
        combo_sales1.addItem("CHOOSE ONE");
        BillInfoDao action=new BillInfoDao();
        bills=action.getAllRecord();
        for(BillInfoTo bill:bills)
        {
            combo_sales1.addItem(bill);
        }
         combo_sale2.removeAllItems();
        combo_sale2.addItem("CHOOSE ONE");
        MedicineInfoDao action1=new MedicineInfoDao();
        meds=action1.getAllRecord();
        for(MedicineInfoTo med:meds)
        {
            combo_sale2.addItem(med);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_sale1 = new javax.swing.JLabel();
        combo_sales1 = new javax.swing.JComboBox();
        lb_sale2 = new javax.swing.JLabel();
        combo_sale2 = new javax.swing.JComboBox();
        lb_sale3 = new javax.swing.JLabel();
        tf_sale1 = new javax.swing.JTextField();
        lb_sale4 = new javax.swing.JLabel();
        tf_sale2 = new javax.swing.JTextField();
        bt_sale = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        lb_sale1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_sale1.setText("CHOOSE BILL :");

        combo_sales1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combo_sales1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_sales1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_sales1ActionPerformed(evt);
            }
        });

        lb_sale2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_sale2.setText("ENTER QUANTITY :");

        combo_sale2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combo_sale2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lb_sale3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_sale3.setText("CHOOSE MEDICINE :");

        tf_sale1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lb_sale4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_sale4.setText("ENTER PRICE :");

        tf_sale2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        bt_sale.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_sale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon.png"))); // NOI18N
        bt_sale.setText("SAVE DETAILS");
        bt_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saleActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go-back-icon.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lb_sale1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lb_sale3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(combo_sales1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_sale2, 0, 299, Short.MAX_VALUE))
                            .addComponent(tf_sale1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_sale2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lb_sale2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lb_sale4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_sale)
                        .addGap(102, 102, 102)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lb_sale1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_sales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_sale3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(combo_sale2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lb_sale2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_sale1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_sale4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_sale2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_sales1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_sales1ActionPerformed
       
    }//GEN-LAST:event_combo_sales1ActionPerformed

    private void bt_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saleActionPerformed
       String msg="";
       SaleDetailTo record=new SaleDetailTo();
       SaleDetailDao action=new SaleDetailDao();
       if(combo_sales1.getSelectedIndex()==0)
       {
           msg+="PLEASE CHOOSE BILL NO \n";
       }
       else
       {
           int bill_no=(int) combo_sales1.getSelectedItem();
           record.setBill_no(bill_no);
          
       }
       if(combo_sale2.getSelectedIndex()==0)
       {
           msg+="PLEASE CHOOSE MEDICINE \n";
       }
       else
       {
           String medicine_code=(String)combo_sale2.getSelectedItem();
           record.setMedicine_code(medicine_code);
       }
       String qty=tf_sale2.getText().trim();
       if(isInteger(qty)||!isEmpty(qty))
       {
          int quantity=Integer.parseInt(qty);
          record.setQty(quantity);
       }
       else
       {
           msg+="PLEASE ENTER A VALID QUANTITY \n";
       }
       String price=tf_sale2.getText().trim();
       if(isFloat(price)||!isEmpty(price))
       {
           float rs=Float.parseFloat(price);
           record.setPrice(rs);
       }
       else
       {
           msg+="ENTER A VALID PRICE \n";
       }
       if(action.insertrecord(record))
       {
           msg+="RECORD IS INSERTED \n";
       }
       else
       {
           msg+=" FAILURE DUE TO "+action.getError_message();
       }
       JOptionPane.showMessageDialog(this,msg);
       
       
    }//GEN-LAST:event_bt_saleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_sale;
    private javax.swing.JComboBox combo_sale2;
    private javax.swing.JComboBox combo_sales1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lb_sale1;
    private javax.swing.JLabel lb_sale2;
    private javax.swing.JLabel lb_sale3;
    private javax.swing.JLabel lb_sale4;
    private javax.swing.JTextField tf_sale1;
    private javax.swing.JTextField tf_sale2;
    // End of variables declaration//GEN-END:variables
}
