/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainscreen;

import javax.swing.JOptionPane;
import model.dao.MedicineInfoDao;
import model.dao.MedicineTypeDao;
import useit.Validations;

/**
 *
 * @author Rahul Saini
 */
public class IfDeleteMedicineInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfDeleteMedcine
     */
    public IfDeleteMedicineInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_medicine1 = new javax.swing.JLabel();
        tf_medicine = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        lb_medicine1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_medicine1.setText("ENTER MEDICINE ID :");

        tf_medicine.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf_medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_medicineActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("DELETE MEDICINE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lb_medicine1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(tf_medicine, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton1)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lb_medicine1)
                .addGap(18, 18, 18)
                .addComponent(tf_medicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_medicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_medicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_medicineActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String msg="";
       String medicine_code=tf_medicine.getText().trim();
       MedicineInfoDao action=new MedicineInfoDao();
       if(!Validations.isEmpty(medicine_code))
       {
       if(action.deleterecord(medicine_code))
       {
           msg+="MEDICINE IS DELETED SUCCESSFULLY\n\n";
       }
       else
       {
           msg+="FAILURE";
       }
       }
       else
       {
           msg+="ENTER A MEDICINE ID \n";
       }    
       JOptionPane.showMessageDialog(this,msg);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lb_medicine1;
    private javax.swing.JTextField tf_medicine;
    // End of variables declaration//GEN-END:variables
}
