/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainscreen;

import javax.swing.JOptionPane;
import model.dao.MedicineTypeDao;
import useit.Validations;

/**
 *
 * @author Rahul Saini
 */
public class IfDeleteMedicineType extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfDeleteMedcineType
     */
    public IfDeleteMedicineType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_type1 = new javax.swing.JLabel();
        tf_type1 = new javax.swing.JTextField();
        bt_deletetype = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        lb_type1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_type1.setText("ENTER MEDICINE TYPE ID :");

        tf_type1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        bt_deletetype.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_deletetype.setText("DELETE TYPE");
        bt_deletetype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletetypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lb_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(tf_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(bt_deletetype, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tf_type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bt_deletetype, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deletetypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletetypeActionPerformed
      String msg="";
       String type_id=tf_type1.getText();
       MedicineTypeDao action=new MedicineTypeDao();
       if(Validations.isEmpty(type_id))
       {
            msg+="please enter a type id";
       }
       else
       {
           if(action.deleteRecord(type_id))
           {
             msg+="MEDICINE TYPE IS DELETED SUCCESSFULLY\n\n";
           }
           else
           {
             msg+="FAILURE";
            }
       }    
       JOptionPane.showMessageDialog(this,msg);
    }//GEN-LAST:event_bt_deletetypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_deletetype;
    private javax.swing.JLabel lb_type1;
    private javax.swing.JTextField tf_type1;
    // End of variables declaration//GEN-END:variables
}
