/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainscreen;

import javax.swing.JOptionPane;
import model.dao.CustomerDao;
import useit.Validations;

/**
 *
 * @author Rahul Saini
 */
public class IfDeleteCustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfDeleteCustomer
     */
    public IfDeleteCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_customer1 = new javax.swing.JLabel();
        tf_customer = new javax.swing.JTextField();
        bt_customer = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        lb_customer1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_customer1.setText("ENTER CUSTOMER ID :");

        tf_customer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_customerActionPerformed(evt);
            }
        });

        bt_customer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        bt_customer.setText("DELETE CUSTOMER");
        bt_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_customerActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go-back-icon.png"))); // NOI18N
        jButton2.setText("BACK");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(lb_customer1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bt_customer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(tf_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lb_customer1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_customerActionPerformed

    private void bt_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_customerActionPerformed
      String msg="";
       String customer_code=tf_customer.getText().trim();
       CustomerDao action=new CustomerDao();
       if(Validations.isEmpty(customer_code))
       {
           msg+="PLEASE ENTER SOME VALUE \n";
       }   
       else if(Validations.isInteger(customer_code))
       {
           int code=Integer.parseInt(customer_code);
           if(action.deleterecord(code))
           {
              msg+="CUSTOMER IS DELETED SUCCESSFULLY\n\n";
           }
           else
           {
             msg+="FAILURE";
           }
       }
       else
       {
           msg+="ENTER A VALID CUSTOMER ID \n";
       }    
       JOptionPane.showMessageDialog(this,msg);
    }//GEN-LAST:event_bt_customerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_customer;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lb_customer1;
    private javax.swing.JTextField tf_customer;
    // End of variables declaration//GEN-END:variables
}
