/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainscreen;

import javax.swing.JOptionPane;
import model.dao.MedicineInfoDao;
import model.dao.SupplierDao;
import useit.Validations;

/**
 *
 * @author Rahul Saini
 */
public class IfDeleteSupplier extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfDeleteSupplier
     */
    public IfDeleteSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_supplier = new javax.swing.JLabel();
        tf_supplier = new javax.swing.JTextField();
        bt_supplier = new javax.swing.JButton();

        lb_supplier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_supplier.setText("ENTER SUPPLIER ID");

        tf_supplier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        bt_supplier.setText("DELETE SUPPLIER");
        bt_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(tf_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(bt_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(bt_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supplierActionPerformed
        String msg="";
       String supplier_code=tf_supplier.getText().trim();
       SupplierDao action=new SupplierDao();
       if(!Validations.isEmpty(supplier_code))
       {
       if(action.deleterecord(supplier_code))
       {
           msg+="SUPPLIER IS DELETED SUCCESSFULLY\n\n";
       }
       else
       {
           msg+="FAILURE";
       }
       }
       else
       {
           msg+="ENTER A SUPPLIER ID \n";
       }    
       JOptionPane.showMessageDialog(this,msg);
    }//GEN-LAST:event_bt_supplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_supplier;
    private javax.swing.JLabel lb_supplier;
    private javax.swing.JTextField tf_supplier;
    // End of variables declaration//GEN-END:variables
}
