/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainscreen;

import model.to.CustomerTo;
import model.to.MedicineInfoTo;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.BillInfoDao;
import model.dao.CustomerDao;
import model.dao.MedicineInfoDao;
import model.dao.StockDao;
import model.to.BillInfoTo;
import model.to.StockTo;

/**
 *
 * @author Rahul Saini
 */
public class IfSales extends javax.swing.JInternalFrame {

    private List<CustomerTo>cus; 
    private List<MedicineInfoTo>medicines;
    private List<StockTo> stock;
    private JPopupMenu popup;
    private int selected_row;
    CustomerTo customer=new CustomerTo();
    CustomerDao action1=new CustomerDao();
    MedicineInfoTo record1=new MedicineInfoTo();
    MedicineInfoDao action2=new MedicineInfoDao();
    public IfSales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
