/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainscreen;

import javax.swing.JOptionPane;
import model.dao.CompanyInfoDao;
import model.to.CompanyInfoTo;
import useit.Validations;

/**
 *
 * @author Rahul Saini
 */
public class IfUpdateCompany extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfUpdateCompany
     */
    public IfUpdateCompany() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_company4 = new javax.swing.JLabel();
        tf_company41 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_company42 = new javax.swing.JTextField();
        bt_company4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        lb_company4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb_company4.setText("ENTER COMPANY ID : ");

        tf_company41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_company41ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("ENTER UPDATED NAME :");

        tf_company42.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        bt_company4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_company4.setText("UPDATE COMAPNY");
        bt_company4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_company4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lb_company4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(bt_company4)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_company41, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(tf_company42))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_company4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_company41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tf_company42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bt_company4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_company41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_company41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_company41ActionPerformed

    private void bt_company4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_company4ActionPerformed
        String message="";
        String company_id=tf_company41.getText().trim();
        String company_name=tf_company42.getText().trim();
        if(Validations.isEmpty(company_id)||Validations.isEmpty(company_name))
        {
            message+="Please fill all the boxes \n";
        }
        else
        {    
          CompanyInfoTo record=new CompanyInfoTo();
          record.setCompany_id(company_id);
          record.setCompany_name(company_name);
          CompanyInfoDao action=new CompanyInfoDao();
          if(action.updateRecord(record))
          {
             message+=" company is UPDATED \n";
            
          }
          else{
          message="failure \n";
        }
       }  
        JOptionPane.showMessageDialog(this,message);    
    }//GEN-LAST:event_bt_company4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_company4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_company4;
    private javax.swing.JTextField tf_company41;
    private javax.swing.JTextField tf_company42;
    // End of variables declaration//GEN-END:variables
}
