/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainscreen;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.dao.CompanyInfoDao;
import model.to.CompanyInfoTo;

/**
 *
 * @author Rahul Saini
 */
public class IfViewCompany extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfViewCompany
     */
    private List<CompanyInfoTo> companies;
    
    public IfViewCompany() {
        initComponents();
        bindTableCompany();
    }
    private void bindTableCompany()
    {
        String[] col_names={"Company ID","Company Name"};
        Object[][] records=null;
        companies=new CompanyInfoDao().getAllRecord();
        if(companies!=null&&companies.size()>0)
        {
            records=new Object[companies.size()][col_names.length];
            int index=0;
            for(CompanyInfoTo cm:companies)
            {
                records[index]=new Object[]{cm.getCompany_id(),cm.getCompany_name()};
                index++;
            }
        }   
        else{
            records=new Object[1][col_names.length];
            records[0]=new Object[]{"NO INFORMATION IS PRESENT","NO INFORMATON IS PRESENT"};
        }
            
        DefaultTableModel model=new DefaultTableModel(records,col_names);
        table_company1.setModel(model);
               
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_company1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("VIEW LIST OF COMPANIES");
        setToolTipText("");

        table_company1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_company1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_company1;
    // End of variables declaration//GEN-END:variables
}
