/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package controls;

import java.sql.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import useit.ErrorHandler;

/**
 *
 * @author Rahul Saini
 */
public class DatePanel1 extends javax.swing.JPanel {

     private GregorianCalendar gcal;
    /**
     * Creates new form DatePanel
     */
    public DatePanel1() {
        initComponents();
        gcal = new GregorianCalendar();
        jcbYear.removeAllItems();
        jcbYear.addItem("Year");
        int current_year = gcal.get(Calendar.YEAR);
        for (int year = 2050; year >= current_year; year--)
        {
           jcbYear.addItem(year);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbYear = new javax.swing.JComboBox();
        jcbMonth = new javax.swing.JComboBox();
        jcbDate = new javax.swing.JComboBox();

        jcbYear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbYearItemStateChanged(evt);
            }
        });

        jcbMonth.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbMonthItemStateChanged(evt);
            }
        });

        jcbDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jcbDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jcbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbDate, 0, 79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jcbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jcbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jcbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbYearItemStateChanged
        int month_selected_index = jcbMonth.getSelectedIndex();
        int date_selected_index = jcbDate.getSelectedIndex();
        jcbMonth.removeAllItems();
        jcbMonth.addItem("Month");
        if (jcbYear.getSelectedIndex() > 0) {
            int selected_year = Integer.parseInt(jcbYear.getSelectedItem().toString());
            int current_year = gcal.get(Calendar.YEAR);
            MonthList[] months = MonthList.values();
            int begin_index=0;
            int end_index = months.length - 1;
            if (selected_year == current_year) {
                begin_index = gcal.get(Calendar.MONTH);
            }
            for (int index = begin_index; index <= end_index; index++) {
                jcbMonth.addItem(months[index]);
            }
            if (month_selected_index < jcbMonth.getItemCount()) {
                jcbMonth.setSelectedIndex(month_selected_index);
            }
            if (date_selected_index < jcbDate.getItemCount()) {
                jcbDate.setSelectedIndex(date_selected_index);
            }
        }
    }//GEN-LAST:event_jcbYearItemStateChanged

    private void jcbMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbMonthItemStateChanged
      int date_selected_index = jcbDate.getSelectedIndex();
        jcbDate.removeAllItems();
        jcbDate.addItem("Date");
        if (jcbMonth.getSelectedIndex() > 0) {
            int selected_year = Integer.parseInt(jcbYear.getSelectedItem().toString());
            int current_year = gcal.get(Calendar.YEAR);
            int current_month = gcal.get(Calendar.MONTH);
            MonthList selected_month = (MonthList) jcbMonth.getSelectedItem();
            int start_date = 1;
            int end_date = selected_month.getTotal_days();
            if (selected_year == current_year && current_month == selected_month.ordinal()) {
                start_date = gcal.get(Calendar.DATE);
            } else if (selected_month == MonthList.February) {
                end_date = gcal.isLeapYear(selected_year) ? 29 : 28;
            }
            for (int date = start_date; date <= end_date; date++) {
                jcbDate.addItem(date);
            }
            if (date_selected_index < jcbDate.getItemCount()) {
                jcbDate.setSelectedIndex(date_selected_index);
            }
        }
    }//GEN-LAST:event_jcbMonthItemStateChanged
     
    public Date getSelectedDate() {
        Date selected_date = null;
        try {
            if(jcbYear.getSelectedIndex() > 0 && jcbMonth.getSelectedIndex()>0 && jcbDate.getSelectedIndex() > 0){
                int year = Integer.parseInt(jcbYear.getSelectedItem().toString());
                int month = jcbMonth.getSelectedIndex();
                int date = jcbDate.getSelectedIndex();
                String date_string = year + "-" + month + "-" + date;
                selected_date = Date.valueOf(date_string);
            }
        } catch (Exception ex) {
            ErrorHandler.showErrorStack(ex);
        }
        return selected_date;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jcbDate;
    private javax.swing.JComboBox jcbMonth;
    private javax.swing.JComboBox jcbYear;
    // End of variables declaration//GEN-END:variables
}
